<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="17" total="18" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13975" started-at="2023-09-22T05:44:30Z" finished-at="2023-09-22T05:44:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13975" started-at="2023-09-22T05:44:30Z" finished-at="2023-09-22T05:44:44Z">
      <class name="com.webdriver.testeg.FirstTestLeafgroundAppln">
        <test-method status="PASS" signature="bf()[pri:0, instance:com.webdriver.testeg.FirstTestLeafgroundAppln@60c6f5b]" name="bf" is-config="true" duration-ms="13927" started-at="2023-09-22T11:14:30Z" finished-at="2023-09-22T11:14:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method status="FAIL" signature="dashboard()[pri:0, instance:com.webdriver.testeg.FirstTestLeafgroundAppln@60c6f5b]" name="dashboard" duration-ms="24" started-at="2023-09-22T11:14:44Z" finished-at="2023-09-22T11:14:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dashboard] but found [Dashboard1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dashboard] but found [Dashboard1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.webdriver.testeg.FirstTestLeafgroundAppln.dashboard(FirstTestLeafgroundAppln.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboard -->
        <test-method status="PASS" signature="af()[pri:0, instance:com.webdriver.testeg.FirstTestLeafgroundAppln@60c6f5b]" name="af" is-config="true" duration-ms="1" started-at="2023-09-22T11:14:44Z" finished-at="2023-09-22T11:14:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- af -->
      </class> <!-- com.webdriver.testeg.FirstTestLeafgroundAppln -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
